### PR TITLE
update requires regex to allow tab indentation, fixes #5

### LINKED ISSUE #5: Tab indentation
It shouldn't matter if you use tabs or white spaces for indentation.

Add tests and refactor space related behavior.

### PR DESCRIPTION
**Pull request by dajester2013**

### CODE REVIEW

**Comment by Journerist** [comment]
Hi dejester,

I think it should be fixed for every regex. Also we need a test to make sure tab indentation works for every regex. When tests exist then we should refectory this asap.

You can update your pull request or I will do it as soon as I have time to fix it properly.

**Comment by Journerist** [comment]
I also added an issue #5 to track it.

**Comment by dajester2013** [comment]
This PR is ready for further review.

**Comment by Journerist** [comment]
sorry for being late, I was on holiday.

At first thank you for your additional work. I think you just need to replace all " " (whitespaces) with the /s regexp metacharacter. Does something not pass if you do that?

Also you should complete the tests for all kinds of requires:
-extends
-models
-mixins
-requires

Putting all tests in an extra describe should also centralize the issue in the test file instead of putting a tab related it in different describes.

regards

**Comment by Journerist** [comment]
resolved in #5

**Pull request closed without merging**
