### PR TITLE
removeComments - no space before //

### PR DESCRIPTION
**Pull request by ddragostinov**
observed: 
removeComments("if (visibleCol ){//&& field.name != 'Icon') {") -> if (visibleCol ){//&& field.name != 'Icon') {

expected: 
removeComments("if (visibleCol ){//&& field.name != 'Icon') {") -> if (visibleCol ){

### CODE REVIEW

**Comment by Journerist** [comment]
Hey,

Thank you for contributing. Can you add a test please that verifys the added behavior?

**Comment by ddragostinov** [comment]
Hi, I didn't add a new test case, but added a function which breaks 5 tests without the fix.

**Comment by ddragostinov** [comment]
Just found a new case in our code base, which I guess will be hard to fix without parsing the file to an AST and then stripping comments.

if (url.indexOf('://') == -1) {

When removeComments is called
"if (url.indexOf('://') == -1) {" turns into "if (url.indexOf(':" which eats one opening brace.

I suggest using something like:
https://github.com/jonschlinkert/strip-comments

What do you think?

**Comment by Journerist** [comment]
For now there was no need to create an AST. Probably, the performance will suffer. 

First, let's merge this change. Your example can probably be fixed by adapting the regex again.

However,  you can keep working on the regex or playing around with handy libraries. Regarding the latter I am interested in performance tests. To make sure to keep the runtime under controle.

Thanks for contributing, I will publish the update asap.

**Pull request merged**
