### PR TITLE
Handle more complicated requires:[] and other magic config arrays

### PR DESCRIPTION
**Pull request by altintx**
Instead of grabbing configs with regex, mock up Ext.define and try to grab the evaluated arrays. Fail over to the regex-based solution.

### CODE REVIEW

**Comment by Journerist** [comment]
I like the idea but it's important to ensure that the tests don't break.

Also we need some kind of performance tests. I think using eval in such a central way results in slower execution time. 

I don't like ugly regular expressions too but they are very fast and don't cause any overhead for executing and validating javascript. 

I am confident that we can use your idea to improve parsing ext definitions when the execution time doesn't increase heavily.

**Comment by altintx** [comment]
The regex is failing on
 
```requires:[
	//	"univnm.db",
		"univnm.ext.QueryStore",
		"univnm.ext.SupaGrid",
		"univnm.ext.Notification"

	]```

Perhaps because the comment is the first item in the array

It's instead return the requires statement as "requires:[\n" which eventually turns into a blank array.

**Comment by altintx** [comment]
Also, the failure is stemming from the merge. Reapplying the diff on a fresh repo (I'd previously forked under a previous repo and had to catch up) would avoid that problem. Have no better answer on the eval() though, I'm afraid.

**Comment by Journerist** [comment]
no active conversation

**Comment by altintx** [comment]
Did the failure sample not help to identify the problem with the regex?

**Comment by Journerist** [comment]
I would appreciate some efforts regarding testing the performance. I think it's a crucial requirement to be fast.

Feel free to make use of eval and to compare the speed with the implementation of the master branch. I'm excited for the results but make sure that all existing tests work.

**Pull request closed without merging**
